version: '3'
services:
 
  video-streaming:
    image: video-streaming
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3000:3000"
    environment:
      - VIDEOS=./videos
    restart: always